name: bank-of-anthos-staging
region: syd1
vpc:
  id: 20ccc9c3-2bad-40dc-9669-8d5ef784b765
services:
  - name: frontend
    github:
      repo: YOUR_GITHUB_ORG/bank-of-anthos-codex-app-platform
      branch: main
      deploy_on_push: false
    source_dir: src/frontend
    dockerfile_path: Dockerfile
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: BALANCES_API_ADDR
        value: balancereader:8080
        scope: RUN_TIME
      - key: CONTACTS_API_ADDR
        value: contacts:8080
        scope: RUN_TIME
      - key: TRANSACTIONS_API_ADDR
        value: ledgerwriter:8080
        scope: RUN_TIME
      - key: HISTORY_API_ADDR
        value: transactionhistory:8080
        scope: RUN_TIME
      - key: USERSERVICE_API_ADDR
        value: userservice:8080
        scope: RUN_TIME
      - key: LOCAL_ROUTING_NUM
        value: "883745000"
        scope: RUN_TIME
      - key: USE_DEMO_DATA
        value: "true"
        scope: RUN_TIME
      - key: JWT_PUBLIC_KEY
        value: REPLACE_ME
        type: SECRET
        scope: RUN_TIME
      - key: ENABLE_TRACING
        value: "false"
        scope: RUN_TIME
      - key: ENABLE_METRICS
        value: "false"
        scope: RUN_TIME
  - name: userservice
    github:
      repo: YOUR_GITHUB_ORG/bank-of-anthos-codex-app-platform
      branch: main
      deploy_on_push: false
    source_dir: src/accounts/userservice
    dockerfile_path: Dockerfile
    internal_ports: [8080]
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: POSTGRES_HOST
        value: ${accountsdb.HOST}
        scope: RUN_TIME
      - key: POSTGRES_PORT
        value: ${accountsdb.PORT}
        scope: RUN_TIME
      - key: POSTGRES_USER
        value: ${accountsdb.USER}
        scope: RUN_TIME
      - key: POSTGRES_PASSWORD
        value: ${accountsdb.PASSWORD}
        scope: RUN_TIME
      - key: POSTGRES_DB
        value: accountsdb
        scope: RUN_TIME
      - key: ACCOUNTS_DB_URI
        value: postgresql://${accountsdb.USER}:${accountsdb.PASSWORD}@${accountsdb.HOST}:${accountsdb.PORT}/accountsdb?sslmode=require
        scope: RUN_TIME
      - key: USE_DEMO_DATA
        value: "true"
        scope: RUN_TIME
      - key: LOCAL_ROUTING_NUM
        value: "883745000"
        scope: RUN_TIME
      - key: JWT_PRIVATE_KEY
        value: REPLACE_ME
        type: SECRET
        scope: RUN_TIME
      - key: JWT_PUBLIC_KEY
        value: REPLACE_ME
        type: SECRET
        scope: RUN_TIME
      - key: ENABLE_TRACING
        value: "false"
        scope: RUN_TIME
      - key: ENABLE_METRICS
        value: "false"
        scope: RUN_TIME
  - name: contacts
    github:
      repo: YOUR_GITHUB_ORG/bank-of-anthos-codex-app-platform
      branch: main
      deploy_on_push: false
    source_dir: src/accounts/contacts
    dockerfile_path: Dockerfile
    internal_ports: [8080]
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: POSTGRES_HOST
        value: ${accountsdb.HOST}
        scope: RUN_TIME
      - key: POSTGRES_PORT
        value: ${accountsdb.PORT}
        scope: RUN_TIME
      - key: POSTGRES_USER
        value: ${accountsdb.USER}
        scope: RUN_TIME
      - key: POSTGRES_PASSWORD
        value: ${accountsdb.PASSWORD}
        scope: RUN_TIME
      - key: POSTGRES_DB
        value: accountsdb
        scope: RUN_TIME
      - key: ACCOUNTS_DB_URI
        value: postgresql://${accountsdb.USER}:${accountsdb.PASSWORD}@${accountsdb.HOST}:${accountsdb.PORT}/accountsdb?sslmode=require
        scope: RUN_TIME
      - key: USE_DEMO_DATA
        value: "true"
        scope: RUN_TIME
      - key: LOCAL_ROUTING_NUM
        value: "883745000"
        scope: RUN_TIME
      - key: JWT_PUBLIC_KEY
        value: REPLACE_ME
        type: SECRET
        scope: RUN_TIME
      - key: ENABLE_TRACING
        value: "false"
        scope: RUN_TIME
      - key: ENABLE_METRICS
        value: "false"
        scope: RUN_TIME
  - name: ledgerwriter
    github:
      repo: YOUR_GITHUB_ORG/bank-of-anthos-codex-app-platform
      branch: main
      deploy_on_push: false
    source_dir: src/ledger/ledgerwriter
    dockerfile_path: Dockerfile
    internal_ports: [8080]
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: POSTGRES_HOST
        value: ${ledgerdb.HOST}
        scope: RUN_TIME
      - key: POSTGRES_PORT
        value: ${ledgerdb.PORT}
        scope: RUN_TIME
      - key: POSTGRES_USER
        value: ${ledgerdb.USER}
        scope: RUN_TIME
      - key: POSTGRES_PASSWORD
        value: ${ledgerdb.PASSWORD}
        scope: RUN_TIME
      - key: POSTGRES_DB
        value: ledgerdb
        scope: RUN_TIME
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://${ledgerdb.HOST}:${ledgerdb.PORT}/ledgerdb?sslmode=require
        scope: RUN_TIME
      - key: SPRING_DATASOURCE_USERNAME
        value: ${ledgerdb.USER}
        scope: RUN_TIME
      - key: SPRING_DATASOURCE_PASSWORD
        value: ${ledgerdb.PASSWORD}
        scope: RUN_TIME
      - key: BALANCES_API_ADDR
        value: balancereader:8080
        scope: RUN_TIME
      - key: LOCAL_ROUTING_NUM
        value: "883745000"
        scope: RUN_TIME
      - key: JWT_PUBLIC_KEY
        value: REPLACE_ME
        type: SECRET
        scope: RUN_TIME
      - key: ENABLE_TRACING
        value: "false"
        scope: RUN_TIME
      - key: ENABLE_METRICS
        value: "false"
        scope: RUN_TIME
  - name: balancereader
    github:
      repo: YOUR_GITHUB_ORG/bank-of-anthos-codex-app-platform
      branch: main
      deploy_on_push: false
    source_dir: src/ledger/balancereader
    dockerfile_path: Dockerfile
    internal_ports: [8080]
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: POSTGRES_HOST
        value: ${ledgerdb.HOST}
        scope: RUN_TIME
      - key: POSTGRES_PORT
        value: ${ledgerdb.PORT}
        scope: RUN_TIME
      - key: POSTGRES_USER
        value: ${ledgerdb.USER}
        scope: RUN_TIME
      - key: POSTGRES_PASSWORD
        value: ${ledgerdb.PASSWORD}
        scope: RUN_TIME
      - key: POSTGRES_DB
        value: ledgerdb
        scope: RUN_TIME
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://${ledgerdb.HOST}:${ledgerdb.PORT}/ledgerdb?sslmode=require
        scope: RUN_TIME
      - key: SPRING_DATASOURCE_USERNAME
        value: ${ledgerdb.USER}
        scope: RUN_TIME
      - key: SPRING_DATASOURCE_PASSWORD
        value: ${ledgerdb.PASSWORD}
        scope: RUN_TIME
      - key: LOCAL_ROUTING_NUM
        value: "883745000"
        scope: RUN_TIME
      - key: JWT_PUBLIC_KEY
        value: REPLACE_ME
        type: SECRET
        scope: RUN_TIME
      - key: ENABLE_TRACING
        value: "false"
        scope: RUN_TIME
      - key: ENABLE_METRICS
        value: "false"
        scope: RUN_TIME
  - name: transactionhistory
    github:
      repo: YOUR_GITHUB_ORG/bank-of-anthos-codex-app-platform
      branch: main
      deploy_on_push: false
    source_dir: src/ledger/transactionhistory
    dockerfile_path: Dockerfile
    internal_ports: [8080]
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: POSTGRES_HOST
        value: ${ledgerdb.HOST}
        scope: RUN_TIME
      - key: POSTGRES_PORT
        value: ${ledgerdb.PORT}
        scope: RUN_TIME
      - key: POSTGRES_USER
        value: ${ledgerdb.USER}
        scope: RUN_TIME
      - key: POSTGRES_PASSWORD
        value: ${ledgerdb.PASSWORD}
        scope: RUN_TIME
      - key: POSTGRES_DB
        value: ledgerdb
        scope: RUN_TIME
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://${ledgerdb.HOST}:${ledgerdb.PORT}/ledgerdb?sslmode=require
        scope: RUN_TIME
      - key: SPRING_DATASOURCE_USERNAME
        value: ${ledgerdb.USER}
        scope: RUN_TIME
      - key: SPRING_DATASOURCE_PASSWORD
        value: ${ledgerdb.PASSWORD}
        scope: RUN_TIME
      - key: LOCAL_ROUTING_NUM
        value: "883745000"
        scope: RUN_TIME
      - key: JWT_PUBLIC_KEY
        value: REPLACE_ME
        type: SECRET
        scope: RUN_TIME
      - key: ENABLE_TRACING
        value: "false"
        scope: RUN_TIME
      - key: ENABLE_METRICS
        value: "false"
        scope: RUN_TIME
workers:
  - name: loadgenerator
    github:
      repo: YOUR_GITHUB_ORG/bank-of-anthos-codex-app-platform
      branch: main
      deploy_on_push: false
    source_dir: src/loadgenerator
    dockerfile_path: Dockerfile
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: FRONTEND_ADDR
        value: frontend:8080
        scope: RUN_TIME
      - key: USE_DEMO_DATA
        value: "true"
        scope: RUN_TIME
      - key: ENABLE_TRACING
        value: "false"
        scope: RUN_TIME
      - key: ENABLE_METRICS
        value: "false"
        scope: RUN_TIME
databases:
  - name: accountsdb
    engine: PG
    version: "15"
    size: db-s-dev-database
    num_nodes: 1
    production: true
    cluster_name: boa-staging-postgres
    db_name: accountsdb
    db_user: accounts_user
  - name: ledgerdb
    engine: PG
    version: "15"
    size: db-s-dev-database
    num_nodes: 1
    production: true
    cluster_name: boa-staging-postgres
    db_name: ledgerdb
    db_user: ledger_user
